version: "3.4"

services:
  otg_dev:
    build:
      context: ./
      dockerfile: Dockerfile
    image: otg
    container_name: otg
    restart: always
    tty: true
    privileged: true
    command: /usr/sbin/sshd -D
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    ports:
      - '51824:22'
      - '57788:7788'
    volumes:
        - "../:/app"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

networks:
  default:
    external:
      name: ${NETWORK}